# Додаткові завдання №3

## 1 Перевірка взаємної простоти двох чисел
Реалізуйте алгоритм Евкліда для перевірки взаємної простоти двох чисел (у вигляді функції від двох аргументів).
Виконайте друге завдання з **Домашньої роботи №3** (**Задача 1.3.14**) з використанням даної функції.

In [1]:
# Місце для Вашого коду
import numpy as np
from itertools import combinations


def is_mutually_simple(a, b):
    while a != 0 and b != 0:
        if a > b:
            a = a % b
        else:
            b = b % a
    return a + b == 1

def teor(n, k, p, q):
    amount = [0, 0, 0]
    count = 0
    for el in combinations(range(1, n+1), k):
        count += 1
        if all(map(lambda a: a % p == 0, el)):
            amount[0] += 1
        if all(map(lambda a: a % p == 0 or a % q == 0, el)):
            amount[1] += 1
        if any(map(lambda a: a % p == 0, el)):
            amount[2] += 1

    # just added the checking if p and q are mutually simple
    if not is_mutually_simple(p, q):
        a[1] = None
    return list(map(lambda a: a / count, amount))


def practice(n, k, p, q):
    amount = [0, 0, 0]
    count = 0
    for _ in range(100000):
        el = np.random.choice(range(1, n+1), size=k, replace=False)
        count += 1
        if all(map(lambda a: a % p == 0, el)):
            amount[0] += 1
        if all(map(lambda a: a % p == 0 or a % q == 0, el)):
            amount[1] += 1
        if any(map(lambda a: a % p == 0, el)):
            amount[2] += 1

    # just added the checking if p and q are mutually simple
    if not is_mutually_simple(p, q):
        a[1] = None
    return list(map(lambda a: a / count, amount))


for el in [(25, 5, 3, 4), (25, 10, 3, 4)]:
    print('teoretical for {}: {}'.format(el, teor(*el)))
    print('empirical for {}: {}'.format(el, practice(*el)))


teoretical for (25, 5, 3, 4): [0.001054018445322793, 0.014906832298136646, 0.8835309617918313]
empirical for (25, 5, 3, 4): [0.00107, 0.01463, 0.88446]
teoretical for (25, 10, 3, 4): [0.0, 2.0191142818683536e-05, 0.9940503432494279]
empirical for (25, 10, 3, 4): [0.0, 1e-05, 0.99396]


## 2 Аналіз функцій з класу *numpy.random*
Проаналізуйте взаємозв'язок між функціями з класу **numpy.random**:
- [rand](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.rand.html)
- [randint](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html)
- [random_integers](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_integers.html)
- [random_sample](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_sample.html)
- [random](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random.html)
- [ranf](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.ranf.html)
- [sample](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html)
- [choice](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html)
- [shuffle](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html)
- [permutation](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.permutation.html)

In [2]:
# Місце для Вашого коду та висновків

# однакові функції, в яких тільки відрізняється вигляд параметра size
# зроблено для зручності
print(np.random.rand(3, 2), '\n')
print(np.random.random_sample((3, 2)), '\n')

# в цих функціях документація з random_sample. Скоріш за все, теж зроблено для зручності
print(np.random.random((3, 2)), '\n')
print(np.random.ranf((3, 2)), '\n')
print(np.random.sample((3, 2)), '\n')

# randint(low, hight, size, dtype) генерує випадкове число (або size чисел) з рівномірним дискретним розподілом з
# напівінтервала [low, hight)
# якщо hight упущений, то з напівінтервала [0, low)
# dtype додатково вказує якого типу буде вертатись результат

# random_integers(low, hight, size) генерує випадкове число (або size чисел) з рівномірним дискретним розподілом з
# відрізка [low, hight]
# якщо hight упущений, то з відрізка [1, low]

print(np.random.randint(1, 15, size=50), '\n')
print(np.random.random_integers(1, 15, size=50), '\n')


# shuffle перемішує список/масив, а permutations створює копію списку/масиву і перемішує її
a = np.arange(1, 100)
print('a: ', a, '\n')
print('permutation: ', np.random.permutation(a), '\n')
print("a didn't change:", a, '\n')
np.random.shuffle(a)
print("after shuffle:", a, '\n')


[[0.16601651 0.98897549]
 [0.11555448 0.66698029]
 [0.05855759 0.50273712]] 

[[0.64714883 0.68865304]
 [0.20984772 0.14468761]
 [0.0357907  0.1890248 ]] 

[[0.40743354 0.04674506]
 [0.75902159 0.89375506]
 [0.85042719 0.47917753]] 

[[0.8852374  0.85878388]
 [0.60707587 0.01489572]
 [0.67792343 0.0401878 ]] 

[[0.15584973 0.42432085]
 [0.17052232 0.33565795]
 [0.19033692 0.62861835]] 

[ 6  1 12  8  2  2  8 11 13  8  3 13 10  2 10  3 12  3 10  8  3  3 11  8
  3  1  4  9  5  2  6  6  1  4 10  8  1  5  5  8  3  5 13 10  5 13 12  6
 13  8] 

[ 8  7 11  4  6 13 14  2  7 14  7  8  7  3  9 14  9  2  4 14  4  1  4 15
  6  9  6  1 10  5  4 15  3  6  1  7 13  4 11 12 15  8  5 15  7  3 10  1
  6 13] 

a:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 9

C:\Users\TheGodfather\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:23: DeprecationWarning: This function is deprecated. Please call randint(1, 15 + 1) instead
