# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['2' '4.5' 'top' 'top' 'top' 'top' 'top' 'top' '4.5' 'bottom']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [3]:
# Місце для Вашого коду
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
print(np.random.choice(a, size=(1), replace=False))


[2]


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [4]:
# Місце для Вашого коду
print(np.random.choice(a, size=(4, 6), replace=True))


[[6 8 2 3 5 7]
 [4 4 3 0 3 6]
 [9 6 8 4 3 3]
 [3 1 4 9 1 0]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[4 2 1 0 2 1 2 4 4 1]


Згенеруйте одну випадкову цифру.

In [6]:
# Місце для Вашого коду
print(np.random.randint(10))


4


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [7]:
# Місце для Вашого коду
print(np.random.randint(10, 100, size=(4, 5)))


[[24 10 74 49 61]
 [77 13 97 81 58]
 [24 84 55 33 45]
 [92 45 91 39 74]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.533320485957872


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [9]:
# Місце для Вашого коду

np.random.sample(size=(3, 4))

array([[0.55528748, 0.52779392, 0.88175581, 0.17470615],
       [0.35144972, 0.21345046, 0.37443907, 0.49073016],
       [0.16661146, 0.23021395, 0.75296128, 0.14690564]])

Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [11]:
# Місце для Вашого коду

(np.random.sample(size=10)) * (b - a) + a

array([4.61705703, 4.47684578, 3.15754212, 3.25267872, 3.47043916,
       3.36115273, 4.53861887, 3.82929439, 3.4723731 , 3.15487499])

### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[2 0 7 6 8 5 9 4 1 3]


Перетасуйте матрицю $M$.

In [13]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
# Місце для Вашого коду
M = M.reshape(1, 20)[0]
np.random.shuffle(M)
print(M.reshape(4, 5))


[[11 16  6 10 12]
 [ 5  3  9  4  8]
 [ 7 18 19  2  0]
 [13 15 17  1 14]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [20]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [21]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [22]:
# Місце для Вашого коду

tosses = np.random.choice(['H', 'T'], p=[0.5, 0.5], size=100)
heads = list(tosses).count('H')
tails = list(tosses).count('T')
print("{} heads, and {} tails".format(heads, tails))

50 heads, and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [23]:
# Місце для Вашого коду

tosses = np.random.randint(2, size=100)
heads = list(tosses).count(1)
tails = list(tosses).count(0)
print("{} heads, and {} tails".format(heads, tails))

49 heads, and 51 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [24]:
# Місце для Вашого коду
tosses = list(map(int, map(round, np.random.sample(size=100))))
heads = tosses.count(1)
tails = tosses.count(0)
print(tosses)
print("{} heads, and {} tails".format(heads, tails))


[0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1]
59 heads, and 41 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [25]:
# Місце для Вашого коду
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    tmp_tosses = list(np.random.randint(0, 2, size=n))
    tmp = tmp_tosses.count(1)
    print("n = {}, amount of heads = {}, probability = {}".format(n, tmp, tmp / n))


n = 10, amount of heads = 5, probability = 0.5
n = 50, amount of heads = 30, probability = 0.6
n = 100, amount of heads = 54, probability = 0.54
n = 250, amount of heads = 113, probability = 0.452
n = 500, amount of heads = 246, probability = 0.492
n = 1000, amount of heads = 473, probability = 0.473
n = 2500, amount of heads = 1271, probability = 0.5084
n = 5000, amount of heads = 2485, probability = 0.497
n = 10000, amount of heads = 5003, probability = 0.5003


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [26]:
# Місце для Вашого коду
test = list(np.random.randint(1, 7, size=60))
print(test)
for i in range(1, 7):
    print("n = {}, amount = {}".format(i, test.count(i)))

[3, 4, 4, 4, 6, 1, 3, 6, 3, 6, 6, 1, 3, 6, 1, 2, 5, 6, 4, 1, 1, 6, 1, 2, 1, 5, 5, 4, 2, 5, 6, 3, 3, 3, 6, 1, 6, 1, 3, 4, 4, 1, 3, 6, 4, 1, 6, 3, 2, 3, 3, 6, 6, 5, 5, 6, 6, 2, 2, 3]
n = 1, amount = 11
n = 2, amount = 6
n = 3, amount = 13
n = 4, amount = 8
n = 5, amount = 6
n = 6, amount = 16


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [27]:
# Місце для Вашого коду
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    test = list(np.random.randint(1, 7, size=n))
    probabilities = [test.count(_)/n for _ in range(1, 7)]
    print("n = {}, probabilities = {}".format(n, probabilities))
print(1/6)


n = 10, probabilities = [0.2, 0.1, 0.2, 0.2, 0.2, 0.1]
n = 50, probabilities = [0.16, 0.14, 0.2, 0.18, 0.2, 0.12]
n = 100, probabilities = [0.19, 0.16, 0.15, 0.17, 0.1, 0.23]
n = 250, probabilities = [0.16, 0.148, 0.164, 0.2, 0.196, 0.132]
n = 500, probabilities = [0.164, 0.158, 0.15, 0.18, 0.14, 0.208]
n = 1000, probabilities = [0.154, 0.184, 0.163, 0.161, 0.167, 0.171]
n = 2500, probabilities = [0.1708, 0.1672, 0.1576, 0.17, 0.1696, 0.1648]
n = 5000, probabilities = [0.1724, 0.1774, 0.1614, 0.1588, 0.1616, 0.1684]
n = 10000, probabilities = [0.1631, 0.1609, 0.1628, 0.1738, 0.1764, 0.163]
0.16666666666666666


## 5 Колода карт
### 5.1 Реалізація

In [28]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('J', '♢'), ('J', '♠'), ('J', '♡'), ('J', '♣'), ('1', '♢'), ('1', '♠'), ('1', '♡'), ('1', '♣'), ('Q', '♢'), ('Q', '♠'), ('Q', '♡'), ('Q', '♣'), ('10', '♢'), ('10', '♠'), ('10', '♡'), ('10', '♣'), ('3', '♢'), ('3', '♠'), ('3', '♡'), ('3', '♣'), ('6', '♢'), ('6', '♠'), ('6', '♡'), ('6', '♣'), ('9', '♢'), ('9', '♠'), ('9', '♡'), ('9', '♣'), ('5', '♢'), ('5', '♠'), ('5', '♡'), ('5', '♣'), ('2', '♢'), ('2', '♠'), ('2', '♡'), ('2', '♣'), ('K', '♢'), ('K', '♠'), ('K', '♡'), ('K', '♣'), ('4', '♢'), ('4', '♠'), ('4', '♡'), ('4', '♣'), ('7', '♢'), ('7', '♠'), ('7', '♡'), ('7', '♣'), ('8', '♢'), ('8', '♠'), ('8', '♡'), ('8', '♣')]


In [29]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

J♢, J♠, J♡, J♣, 1♢, 1♠, 1♡, 1♣, Q♢, Q♠, Q♡, Q♣, 10♢, 10♠, 10♡, 10♣, 3♢, 3♠, 3♡, 3♣, 6♢, 6♠, 6♡, 6♣, 9♢, 9♠, 9♡, 9♣, 5♢, 5♠, 5♡, 5♣, 2♢, 2♠, 2♡, 2♣, K♢, K♠, K♡, K♣, 4♢, 4♠, 4♡, 4♣, 7♢, 7♠, 7♡, 7♣, 8♢, 8♠, 8♡, 8♣


In [30]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♢J, ♢1, ♢Q, ♢10, ♢3, ♢6, ♢9, ♢5, ♢2, ♢K, ♢4, ♢7, ♢8
♠J, ♠1, ♠Q, ♠10, ♠3, ♠6, ♠9, ♠5, ♠2, ♠K, ♠4, ♠7, ♠8
♡J, ♡1, ♡Q, ♡10, ♡3, ♡6, ♡9, ♡5, ♡2, ♡K, ♡4, ♡7, ♡8
♣J, ♣1, ♣Q, ♣10, ♣3, ♣6, ♣9, ♣5, ♣2, ♣K, ♣4, ♣7, ♣8


In [31]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('8', '♠'), ('2', '♠'), ('10', '♠'), ('6', '♠'), ('7', '♡'), ('3', '♣'), ('2', '♣'), ('7', '♣'), ('1', '♠'), ('9', '♡'), ('7', '♠'), ('3', '♢'), ('J', '♠'), ('9', '♣'), ('10', '♢'), ('8', '♣'), ('2', '♡'), ('Q', '♢'), ('J', '♡'), ('4', '♣'), ('4', '♠'), ('Q', '♣'), ('Q', '♡'), ('10', '♣'), ('5', '♣'), ('Q', '♠'), ('3', '♡'), ('10', '♡'), ('K', '♢'), ('2', '♢'), ('9', '♠'), ('8', '♡'), ('1', '♣'), ('3', '♠'), ('5', '♠'), ('4', '♡'), ('7', '♢'), ('1', '♢'), ('K', '♠'), ('5', '♡'), ('9', '♢'), ('4', '♢'), ('J', '♢'), ('8', '♢'), ('K', '♣'), ('6', '♡'), ('1', '♡'), ('K', '♡'), ('6', '♢'), ('J', '♣'), ('6', '♣'), ('5', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [32]:
# Місце для Вашого коду
norm_cards = list(map(lambda a: str(a[0]) + ' ' + str(a[1]), Cards))
print(norm_cards)
for n in [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]:
    test = np.random.choice(norm_cards, size=n, replace=True)
    amount = len([el for el in test if el[0] in ['2', '4', '6', '8', '10']])
    print("n = {}, amount of even cards = {}, probability = {}".format(n, amount, amount/n))


['8 ♠', '2 ♠', '10 ♠', '6 ♠', '7 ♡', '3 ♣', '2 ♣', '7 ♣', '1 ♠', '9 ♡', '7 ♠', '3 ♢', 'J ♠', '9 ♣', '10 ♢', '8 ♣', '2 ♡', 'Q ♢', 'J ♡', '4 ♣', '4 ♠', 'Q ♣', 'Q ♡', '10 ♣', '5 ♣', 'Q ♠', '3 ♡', '10 ♡', 'K ♢', '2 ♢', '9 ♠', '8 ♡', '1 ♣', '3 ♠', '5 ♠', '4 ♡', '7 ♢', '1 ♢', 'K ♠', '5 ♡', '9 ♢', '4 ♢', 'J ♢', '8 ♢', 'K ♣', '6 ♡', '1 ♡', 'K ♡', '6 ♢', 'J ♣', '6 ♣', '5 ♢']
n = 10, amount of even cards = 2, probability = 0.2
n = 50, amount of even cards = 14, probability = 0.28
n = 100, amount of even cards = 25, probability = 0.25
n = 250, amount of even cards = 71, probability = 0.284
n = 500, amount of even cards = 150, probability = 0.3
n = 1000, amount of even cards = 316, probability = 0.316
n = 2500, amount of even cards = 733, probability = 0.2932
n = 5000, amount of even cards = 1508, probability = 0.3016
n = 10000, amount of even cards = 3183, probability = 0.3183


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [33]:
# Місце для Вашого коду
hands = [[] for i in range(4)]
for i, suit in enumerate(Suits):
    current_hand = [(suit, rank) for rank in Ranks]
    np.random.shuffle(current_hand)
    for h in range(4):
        card_num = 4 if i==h else 3
        hands[h] += current_hand[:card_num]
        current_hand = current_hand[card_num:]

for hand in hands:
    np.random.shuffle(hand)
    print(', '.join((suit+rank) for suit, rank in hand))


♡Q, ♠3, ♢4, ♣8, ♡3, ♠2, ♣Q, ♢10, ♡8, ♣10, ♢8, ♢9, ♠7
♡7, ♣4, ♣7, ♡10, ♢Q, ♣1, ♠Q, ♢K, ♡2, ♠9, ♢6, ♠K, ♠5
♠1, ♡4, ♢J, ♢1, ♣3, ♣J, ♢3, ♣5, ♡5, ♡1, ♠6, ♠10, ♡6
♡K, ♡9, ♠4, ♣6, ♢7, ♣K, ♣2, ♠J, ♢5, ♢2, ♠8, ♣9, ♡J


### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [34]:
# Місце для Вашого коду
def get_random_split(low, high):
    summ = 13
    ind = []
    while True:
        ind = np.random.randint(low=2, high=6, size=(3, 3))
        a_row = np.array([13 - np.apply_along_axis(sum, 0, ind)])
        if all(a_row[0] <= 5) and all(a_row[0] >= 2):
            ind = np.concatenate((ind, a_row), axis=0)
            a_col = np.array([13 - np.apply_along_axis(sum, 1, ind)])
            if all(a_col[0] <= 5) and all(a_col[0] >= 2):
                ind = np.concatenate((ind, a_col.T), axis=1)
                break

    return ind

hands = [[] for i in range(4)]
split = get_random_split(2, 5)
for i, suit in enumerate(Suits):
    current_hand = [(suit, rank) for rank in Ranks]
    np.random.shuffle(current_hand)
    for j, card_num in enumerate(split[i]):
        hands[j] += current_hand[:card_num]
        current_hand = current_hand[card_num:]

for hand in hands:
    np.random.shuffle(hand)
    print(', '.join((suit+rank) for suit, rank in hand))


♠8, ♣5, ♣Q, ♠1, ♣1, ♡7, ♢10, ♣J, ♢Q, ♢8, ♡K, ♣3, ♠3
♡J, ♠5, ♣10, ♠J, ♡Q, ♢5, ♣K, ♠10, ♢2, ♣2, ♢7, ♡1, ♠6
♠4, ♡2, ♢6, ♠2, ♣7, ♠7, ♡6, ♢J, ♣9, ♠9, ♡4, ♡10, ♢3
♢1, ♡8, ♡9, ♣8, ♢4, ♢9, ♣6, ♣4, ♡3, ♢K, ♡5, ♠K, ♠Q
